# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AndrÃ© Luiz Peron Martins Lanna 
email: 
description: > # this means to ignore newlines until "baseurl:"
  Assistant teacher at University of Brasilia.
  

  PhD Student of Computer Science at University of Brasilia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-96343238-1
twitter_username: andreperon
github_username: andrelanna

# Build settings
markdown: kramdown
#markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true) 
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
